name: Build & Deploy to Azure

on:
  push:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check secret exists
        run: |
          if [ -z "${{ secrets.AZURE_PUBLISH_PROFILE }}" ]; then
            echo "SECRET ESTÁ VACÍO TODAVÍA"
          else
            echo "SECRET tiene contenido"
          fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .