name: Build & Deploy to Azure
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t just-plants-app-service .
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }} // Falta configurar en secrets
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} // Falta configurar en secrets
